language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
  jwt:
    secure: V/8xetU8EnjeJr79lb1662WS7e9UrXyJPKa7tzcuDQ5SU3TV++ViVavN85smBeybg0jfCRma18SnaQW0TwMIzfgHIg0RtpbGuo2TNc2nne4sVGBTidhHrQ6QnlsDk435p5uXqJG05DNAHejWaQHvem/yTaXZ+Zw2gfMs5g9168xgyv+VNd0rUowfn8ZVAFBUyorBE5EoiEaBh12a+OsDgW0vHSYg1BF+xCaEniJm8j4NsIjC05BMwsBz4/PUrTjRjIaTX1rBlcD17c6aihtyhvDZJ5vW7UdAxSQ4s3876c/GNHrX9Ar1pqdQk8NkrN838aBHO34E8KKfPSuKcJZq49p6NBNUXbzKfPwuyG6Bc5qV8/qOVgbwY8X9B9drHkixFE/uHZ+xqpdNf+eN6TlKs7oalPPYPCdQHnCeNQgAuU52GBHCiuRrOobgZIIH+ieBnf+M6pggfPDfbXVYnC6XAVCS3NuO8SaNY+Ym4pxkenNGWYGbIb5N/1lxA3Srqk/DONldLOBNjJxfKuhVwmI8bhxqRCIS9nqazHbnoG4+195Tu4V7d7N+TFcTj/XFArO+fSKZHHUXUMir6X6TofR1KlreEcXhHSBY9TJtMkyhTXpMv6LVdBsK48s7wyXq3q1EDmOQ8yvStVvSauzYWTOwPAiKIiq2TsqYKT3nutYqu4s=
before_install:
  - nvm install 5
  - npm install -g lerna@2.0.0-beta.30
  - lerna bootstrap
install:
  - npm i
script: travis_wait gulp test:saucelabs
