language: java
jdk:
- oraclejdk8
addons:
  sauce_connect:
    username: "fernandosouza"
  jwt:
    secure: "KBMNBw240ZWocYHcsuPhwkrHRKTECmxRB8W+0+4GYz+tqi3sBL/Fj3pMRmYGN16XvT3+ewCU3vTwT23TTRImDUgbffe+u/e0mI8n6f0Ay9M//URbtcNk6lRfic+NJw15H3ma8A3LTlqU7b3qZxQ2fVHBR/ILlsroqmCTJvCteMgQ/vAYJY/4wTkz0ZbiSY98ORtUh1FKA9CBpAC1QO/Qb5mTOPgnSYd0m136xD4soyT6M11K0kJh2YjOtRUBgBBCPg5s+YjWOoWJ9QYOade77IlHxTEVD8K7sL1T+RFjOJimhVud7YbK6QhXveDdSJXcUQrzO77RC2mlhGoiqwdhF89+Z1YnFwjN+Trg/PrCAc+8XmfhUfr7jAbFLm+cdM2GyUfiFh96RA6vlsn/uGcyEpDspfr7heq6YDPz8QYccCjvDXTmQGaUKGkQnJGNtd49HdFudkLe7xQkUXHzttFAH3Ew0oYfEI09lU7cFTfHE8ok9Bj8Nc/exS87w4imOZizYYorfrw5ho1sIS4dNSYn/HRxizcZkRgqVfSrEm3JoauzGh8swtIocf0Zw0iaDbnhCW9oNlzZITngQH8F2kQgn97iLXhxqCtE8XgoanpSI+BY8LNfUy6a3bqUsY5oJTlrpsSzlsSZCrUtcI4zrBpOLZ5bBbl2cGJQ+Fha43ojEfw="
before_install:
- nvm install 5
- npm install -g lerna@2.0.0-beta.30
- lerna bootstrap
install:
- npm i
script: travis_wait gulp test:saucelabs